
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow {
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry entryOne;

	private global::Gtk.Label lblAdd;

	private global::Gtk.Entry entryTwo;

	private global::Gtk.Button btnCalculate;

	private global::Gtk.Button btnPlayMp3;

	protected virtual void Build () {
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition) (4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entryOne = new global::Gtk.Entry ();
		this.entryOne.CanFocus = true;
		this.entryOne.Name = "entryOne";
		this.entryOne.IsEditable = true;
		this.entryOne.InvisibleChar = '●';
		this.hbox1.Add (this.entryOne);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild) (this.hbox1[this.entryOne]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblAdd = new global::Gtk.Label ();
		this.lblAdd.Name = "lblAdd";
		this.lblAdd.LabelProp = global::Mono.Unix.Catalog.GetString ("+");
		this.hbox1.Add (this.lblAdd);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild) (this.hbox1[this.lblAdd]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entryTwo = new global::Gtk.Entry ();
		this.entryTwo.CanFocus = true;
		this.entryTwo.Name = "entryTwo";
		this.entryTwo.IsEditable = true;
		this.entryTwo.InvisibleChar = '●';
		this.hbox1.Add (this.entryTwo);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild) (this.hbox1[this.entryTwo]));
		w3.Position = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnCalculate = new global::Gtk.Button ();
		this.btnCalculate.CanFocus = true;
		this.btnCalculate.Name = "btnCalculate";
		this.btnCalculate.UseUnderline = true;
		this.btnCalculate.Label = global::Mono.Unix.Catalog.GetString ("GO!");
		this.hbox1.Add (this.btnCalculate);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild) (this.hbox1[this.btnCalculate]));
		w4.Position = 3;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild) (this.vbox1[this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnPlayMp3 = new global::Gtk.Button ();
		this.btnPlayMp3.CanFocus = true;
		this.btnPlayMp3.Name = "btnPlayMp3";
		this.btnPlayMp3.UseUnderline = true;
		this.btnPlayMp3.Label = global::Mono.Unix.Catalog.GetString ("Play an MP3 file!");
		this.vbox1.Add (this.btnPlayMp3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild) (this.vbox1[this.btnPlayMp3]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 668;
		this.DefaultHeight = 541;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnCalculate.Clicked += new global::System.EventHandler (this.OnBtnCalculateClicked);
		this.btnPlayMp3.Clicked += new global::System.EventHandler (this.OnBtnPlayMp3Clicked);
	}
}
